name: Build LemonzOS
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Tools and mkosi
        run: |
          sudo apt-get update
          sudo apt-get install -y mkosi systemd-container erofs-utils systemd-repart arch-install-scripts dosfstools mtools

      - name: Build LemonzOS Directory
        run: |
          if [ -f mkosi.postinst ]; then chmod +x mkosi.postinst; fi
          # This builds the OS into a folder called 'image'
          sudo mkosi --force build

      - name: Upload LemonzOS Files
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Filesystem
          path: mkosi.output/
