name: Build LemonzOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mkosi \
            systemd-container \
            debootstrap \
            debian-archive-keyring \
            ovmf \
            erofs-utils \
            systemd-ukify

      - name: Build LemonzOS Image
        run: |
          # Fix the executable permission for the postinst script
          chmod +x mkosi.postinst
          
          # Run the build
          sudo mkosi --force

      - name: Upload LemonzOS
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Output
          path: LemonzOS*
