name: Build LemonzOS
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean and Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mkosi systemd-container erofs-utils systemd-repart arch-install-scripts systemd-ukify python3-pefile
          # Wipe any old build artifacts
          sudo rm -rf mkosi.output/

      - name: Build LemonzOS
        run: |
          chmod +x mkosi.postinst
          sudo mkosi --force build

      - name: Upload LemonzOS
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Package
          path: ./*.raw
