#!/bin/bash
set -e

# Basic system name
echo "lemonzos" > /etc/hostname

# Update the OS name in the settings
if [ -f /etc/os-release ]; then
    sed -i 's/PRETTY_NAME=.*/PRETTY_NAME="LemonzOS"/' /etc/os-release
fi

echo "Post-install script finished successfully."
