name: Build LemonzOS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mkosi \
            systemd-container \
            bubblewrap \
            debootstrap \
            debian-archive-keyring

      - name: Build LemonzOS Image
        run: |
          if [ -f mkosi.postinst ]; then chmod +x mkosi.postinst; fi
          # Force clean before build to avoid 'directory already exists' errors
          sudo mkosi clean
          sudo mkosi build

      - name: Upload LemonzOS Filesystem
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Filesystem
          path: mkosi.output/
