name: Build LemonzOS
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y systemd-container erofs-utils systemd-repart arch-install-scripts systemd-ukify python3-pefile python3-pip dosfstools mtools qemu-utils

      - name: Install mkosi
        run: sudo python3 -m pip install mkosi --break-system-packages

      - name: Build OS
        run: sudo mkosi --force build

      - name: Upload LemonzOS
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Image
          path: image.raw
