name: Build LemonzOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mkosi \
            systemd-container \
            debootstrap \
            debian-archive-keyring \
            ovmf \
            erofs-utils

      - name: Build LemonzOS Image
        run: |
          # FIX: Make the post-install script executable
          sudo chmod +x mkosi.postinst
          
          # Run the build
          sudo mkosi --force

      - name: Upload LemonzOS Filesystem
        uses: actions/upload-artifact@v4
        with:
          name: LemonzOS-Package
          path: |
            LemonzOS*
            mkosi.output/*
          if-no-files-found: warn
